# Generated by Django 6.0.1 on 2026-01-31 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoLicencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(help_text='Nombre para mostrar en la web', max_length=100)),
                ('texto_para_reloj', models.CharField(help_text="Texto exacto que se inyectará en la base vieja (Ej: 'Ausente con aviso')", max_length=100)),
                ('requiere_aviso', models.BooleanField(default=True, help_text='Si requiere validación del jefe')),
                ('es_franquicia', models.BooleanField(default=False, help_text='Si es reducción horaria (Art 55/Lactancia)')),
                ('limite_mensual', models.IntegerField(default=0, help_text='0 = Sin límite')),
                ('limite_anual', models.IntegerField(default=0, help_text='0 = Sin límite')),
            ],
        ),
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.IntegerField(help_text='Número de legajo en RRHH', unique=True)),
                ('id_sistema_reloj', models.IntegerField(blank=True, help_text='ID interno que usa la base de datos del reloj digital (Legacy)', null=True, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(help_text='Para notificaciones automáticas', max_length=254)),
                ('supervisores', models.ManyToManyField(blank=True, help_text='Personas habilitadas para autorizar a este agente', related_name='subordinados', to='core.agente')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateField(help_text='Día de la falta o inicio de licencia')),
                ('dias', models.IntegerField(default=1)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE_VALIDACION', 'Esperando validación de aviso (Jefe)'), ('AVISO_CONFIRMADO', 'Aviso OK - Pasa a RRHH'), ('AVISO_NEGADO', 'Jefe indica SIN AVISO (A Descuento)'), ('APROBADO', 'Finalizado OK (Listo para inyectar)'), ('RECHAZADO', 'Rechazado por RRHH'), ('IMPACTADO', 'Ya inyectado en el Reloj')], default='PENDIENTE_VALIDACION', max_length=30)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='evidencias/')),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='core.agente')),
                ('jefe_seleccionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='avisos_recibidos', to='core.agente')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipolicencia')),
            ],
        ),
    ]
