# Generated by Django 6.0.1 on 2026-02-07 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='certificados/'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='jefe_seleccionado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_a_revisar', to='core.agente'),
        ),
    ]
