# Generated by Django 6.0.1 on 2026-02-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_solicitud_archivo_adjunto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
