# Generated by Django 6.0.1 on 2026-02-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_agente_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='motivo_rechazo',
            field=models.TextField(blank=True, help_text='Razón por la cual RRHH rechazó la solicitud', null=True),
        ),
    ]
