# Generated by Django 6.0.1 on 2026-02-16 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_solicitud_motivo_rechazo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="agente",
            name="fecha_nacimiento",
            field=models.DateField(
                blank=True,
                help_text="Dato obligatorio para activar la cuenta",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="agente",
            name="usuario",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agente_perfil",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
