# Generated by Django 6.0.1 on 2026-02-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_agente_fecha_nacimiento_agente_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='es_rrhh',
            field=models.BooleanField(default=False, help_text='Marcar si esta persona pertenece al Departamento de Personal (Tiene permisos de gestión)'),
        ),
    ]
