# Generated by Django 6.0.1 on 2026-02-17 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_agente_es_rrhh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Servicios Generales, RRHH, Alumnado', max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='agente',
            name='supervisores',
        ),
        migrations.AddField(
            model_name='agente',
            name='categoria',
            field=models.CharField(choices=[('02', '02 - Director'), ('03', '03 - Jefe de Departamento'), ('04', '04 - Jefe de División'), ('05', '05 - Supervisión'), ('06', '06 - Operativo / Ordenanza'), ('07', '07 - Auxiliar / Ordenanza')], default='06', help_text='Define si puede autorizar o no', max_length=2),
        ),
        migrations.AlterField(
            model_name='agente',
            name='es_rrhh',
            field=models.BooleanField(default=False, help_text='Marcar si pertenece a Personal (Gestión Global)'),
        ),
        migrations.AlterField(
            model_name='agente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Dato obligatorio para activar cuenta', null=True),
        ),
        migrations.AlterField(
            model_name='agente',
            name='id_sistema_reloj',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='jefe_seleccionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='avisos_recibidos', to='core.agente'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipolicencia',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tipolicencia',
            name='es_franquicia',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tipolicencia',
            name='limite_anual',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tipolicencia',
            name='limite_mensual',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tipolicencia',
            name='requiere_aviso',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tipolicencia',
            name='texto_para_reloj',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='agente',
            name='area',
            field=models.ForeignKey(blank=True, help_text='Área donde se desempeña', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.area'),
        ),
    ]
